version: "3.9"

services:
  sender-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./server:/usr/src/app
    command: go run main.go -b 0.0.0.0

  app:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: my_python_app
    volumes:
      - .:/app

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    env_file:
      - .env
    restart: "always"
    ports:
      - "5672:5672"
      - "15672:15672" # RabbitMQ Management UI
