version: "3.9"

services:
  app:
    build: .
    container_name: my_python_app
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      MONGO_URI: mongodb://mongo:27017/aiselena_logistic
    volumes:
      - .:/app
